README:
	echo "## Guessing Game Hassan" > README.md
	echo "- The date and time at which this *make* is run is **$$(date '+%d/%m/%Y %H:%M:%S')** " >> README.md
	echo "- The number of lines of code contained in guessinggame.sh is **$$(cat guessinggame.sh | wc -l)** " >> README.md
